/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package intelligent.planning.pkgfor.academics;

import javax.swing.JOptionPane;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Admin
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jusername = new javax.swing.JLabel();
        jpassword = new javax.swing.JLabel();
        typeuser = new javax.swing.JTextField();
        jlogin = new javax.swing.JLabel();
        bexit = new javax.swing.JLabel();
        typepassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        checkbox = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnlogin = new javax.swing.JButton();
        btnsignup = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("LOGIN");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        jLabel2.setText("USERNAME");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 80, 30));

        jLabel3.setBackground(new java.awt.Color(240, 240, 240));
        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("x");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\undraw_building_websites_i78t.png")); // NOI18N
        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jusername.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jusername.setText("USERNAME :");
        jPanel3.add(jusername);
        jusername.setBounds(90, 130, 110, 20);

        jpassword.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jpassword.setText("PASSWORD :");
        jPanel3.add(jpassword);
        jpassword.setBounds(90, 200, 120, 18);

        typeuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeuserActionPerformed(evt);
            }
        });
        jPanel3.add(typeuser);
        typeuser.setBounds(230, 130, 220, 30);

        jlogin.setBackground(new java.awt.Color(255, 255, 255));
        jlogin.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jlogin.setLabelFor(jlogin);
        jlogin.setText("LOGIN !");
        jPanel3.add(jlogin);
        jlogin.setBounds(280, 20, 160, 30);

        bexit.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bexit.setForeground(new java.awt.Color(204, 0, 0));
        bexit.setText("x");
        bexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bexitMouseClicked(evt);
            }
        });
        jPanel3.add(bexit);
        bexit.setBounds(710, 0, 20, 20);

        typepassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typepasswordActionPerformed(evt);
            }
        });
        jPanel3.add(typepassword);
        typepassword.setBounds(230, 190, 220, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/password.png"))); // NOI18N
        jPanel3.add(jLabel7);
        jLabel7.setBounds(30, 190, 50, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(30, 120, 50, 50);

        checkbox.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        checkbox.setText("show password");
        checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxActionPerformed(evt);
            }
        });
        jPanel3.add(checkbox);
        checkbox.setBounds(340, 230, 146, 22);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\Arrowback.png")); // NOI18N
        jLabel9.setText("jLabel9");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel9);
        jLabel9.setBounds(0, 0, 37, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\loginpage.png")); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(260, 270, 470, 370);

        btnlogin.setBackground(new java.awt.Color(255, 0, 153));
        btnlogin.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnlogin.setText("LOGIN");
        btnlogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btnlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnloginMouseClicked(evt);
            }
        });
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        jPanel3.add(btnlogin);
        btnlogin.setBounds(110, 330, 120, 40);

        btnsignup.setBackground(new java.awt.Color(255, 0, 153));
        btnsignup.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnsignup.setText("SIGN UP");
        btnsignup.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btnsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignupActionPerformed(evt);
            }
        });
        jPanel3.add(btnsignup);
        btnsignup.setBounds(110, 400, 120, 40);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 640));

        setSize(new java.awt.Dimension(730, 640));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void typeuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeuserActionPerformed

    private void bexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bexitMouseClicked
System.exit(0);       // TODO add your handling code here:
    }//GEN-LAST:event_bexitMouseClicked

    private void typepasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typepasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typepasswordActionPerformed

    private void checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxActionPerformed
        
    // TODO add your handling code here:
    if(checkbox.isSelected())
        {
            typepassword.setEchoChar((char)0);
        }
        else
        {
          typepassword.setEchoChar('*');
        }
    }//GEN-LAST:event_checkboxActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        homepage hp = new homepage();
        hp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void btnloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnloginMouseClicked
        // TODO add your handling code here:
       assesment plan = new assesment();
        plan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnloginMouseClicked

    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignupActionPerformed
        // TODO add your handling code here:
        signuppage sign = new signuppage();
        sign.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnsignupActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        try{
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/try", "root", "L@yirp6124");
           String jusername=typeuser.getText();
           String jpassword = typepassword.getText();

           Statement stm =con.createStatement();
           String sql = "select * from login where username='"+jusername+"' and password='"+jpassword+"'";
           ResultSet rs = stm.executeQuery(sql);
                System.out.println(rs);
           if(rs.next()){
               
           dispose();
           assesment plan = new assesment();
           plan.show();
           }
           else {

JOptionPane.showMessageDialog(this, "username or password wrong");

typeuser.setText("");
typepassword.setText("");
           }

        con.close();
        }
           catch(Exception e) {

              System.out.println(e.getMessage());
             
        }
    }//GEN-LAST:event_btnloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bexit;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnsignup;
    private javax.swing.JCheckBox checkbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlogin;
    private javax.swing.JLabel jpassword;
    private javax.swing.JLabel jusername;
    private javax.swing.JPasswordField typepassword;
    private javax.swing.JTextField typeuser;
    // End of variables declaration//GEN-END:variables
}
