/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package intelligent.planning.pkgfor.academics;

/**
 *
 * @author Admin
 */
public class nafter10 extends javax.swing.JFrame {

    /**
     * Creates new form nafter10
     */
    public nafter10() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lcs = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        csicon = new javax.swing.JLabel();
        caicon = new javax.swing.JLabel();
        lca = new javax.swing.JLabel();
        animation = new javax.swing.JLabel();
        lanimation = new javax.swing.JLabel();
        creativeicon = new javax.swing.JLabel();
        lcrea = new javax.swing.JLabel();
        archicon = new javax.swing.JLabel();
        larchi = new javax.swing.JLabel();
        coasticon = new javax.swing.JLabel();
        lcoast = new javax.swing.JLabel();
        theatreicon = new javax.swing.JLabel();
        ltheatre = new javax.swing.JLabel();
        gamingicon = new javax.swing.JLabel();
        lgame = new javax.swing.JLabel();
        merchanticon = new javax.swing.JLabel();
        lmerchant = new javax.swing.JLabel();
        philosicon = new javax.swing.JLabel();
        lphilos = new javax.swing.JLabel();
        socialicon = new javax.swing.JLabel();
        lsocial = new javax.swing.JLabel();
        civilsicon = new javax.swing.JLabel();
        lcivils = new javax.swing.JLabel();
        dancericon = new javax.swing.JLabel();
        ldancer = new javax.swing.JLabel();
        archaelogyicon = new javax.swing.JLabel();
        larchaelogy = new javax.swing.JLabel();
        chemistryicon = new javax.swing.JLabel();
        lchemistry = new javax.swing.JLabel();
        cheficon = new javax.swing.JLabel();
        lchef = new javax.swing.JLabel();
        lnextpg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lcs.setText("Company Secretary");
        lcs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lcsMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 0, 153));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\image\\career-listing-header-image.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Your Ideal Career Fit");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("<");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        csicon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ncompany-secretary.png")); // NOI18N
        csicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                csiconMouseClicked(evt);
            }
        });

        caicon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\image\\chartered-accountancy.png")); // NOI18N
        caicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caiconMouseClicked(evt);
            }
        });

        lca.setText("Chartered accountancy");
        lca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lcaMouseClicked(evt);
            }
        });

        animation.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\image\\animation.png")); // NOI18N
        animation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                animationMouseClicked(evt);
            }
        });

        lanimation.setText("Animator");
        lanimation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lanimationMouseClicked(evt);
            }
        });

        creativeicon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\image\\creative-writing.png")); // NOI18N
        creativeicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creativeiconMouseClicked(evt);
            }
        });

        lcrea.setText("Creative-Writing");
        lcrea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lcreaMouseClicked(evt);
            }
        });

        archicon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\image\\architect.png")); // NOI18N
        archicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                archiconMouseClicked(evt);
            }
        });

        larchi.setText("Architect");
        larchi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                larchiMouseClicked(evt);
            }
        });

        coasticon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\image\\coast-guard.png")); // NOI18N
        coasticon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coasticonMouseClicked(evt);
            }
        });

        lcoast.setText("Coast-Guard");
        lcoast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lcoastMouseClicked(evt);
            }
        });

        theatreicon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\image\\dramatics.png")); // NOI18N
        theatreicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                theatreiconMouseClicked(evt);
            }
        });

        ltheatre.setText("Theatre Artist  ");
        ltheatre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ltheatreMouseClicked(evt);
            }
        });

        gamingicon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\12image\\graphic-designing (1).png")); // NOI18N
        gamingicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gamingiconMouseClicked(evt);
            }
        });

        lgame.setText("Graphical Desiginer");
        lgame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lgameMouseClicked(evt);
            }
        });

        merchanticon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\image\\merchant-navy.png")); // NOI18N
        merchanticon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                merchanticonMouseClicked(evt);
            }
        });

        lmerchant.setText("Merchant-Navy");
        lmerchant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lmerchantMouseClicked(evt);
            }
        });

        philosicon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\image\\philosophy.png")); // NOI18N
        philosicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                philosiconMouseClicked(evt);
            }
        });

        lphilos.setText("Philosophy");
        lphilos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lphilosMouseClicked(evt);
            }
        });

        socialicon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\image\\social-work.png")); // NOI18N
        socialicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                socialiconMouseClicked(evt);
            }
        });

        lsocial.setText("Social-Work");
        lsocial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lsocialMouseClicked(evt);
            }
        });

        civilsicon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\image\\civil-services.png")); // NOI18N
        civilsicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                civilsiconMouseClicked(evt);
            }
        });

        lcivils.setText("civil-services");
        lcivils.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lcivilsMouseClicked(evt);
            }
        });

        dancericon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\image\\dance.png")); // NOI18N
        dancericon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dancericonMouseClicked(evt);
            }
        });

        ldancer.setText("dancer");
        ldancer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ldancerMouseClicked(evt);
            }
        });

        archaelogyicon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\image\\archaeology.png")); // NOI18N
        archaelogyicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                archaelogyiconMouseClicked(evt);
            }
        });

        larchaelogy.setText("archaeology");
        larchaelogy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                larchaelogyMouseClicked(evt);
            }
        });

        chemistryicon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\image\\chemistry.png")); // NOI18N
        chemistryicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chemistryiconMouseClicked(evt);
            }
        });

        lchemistry.setText("chemistry");
        lchemistry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lchemistryMouseClicked(evt);
            }
        });

        cheficon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\image\\culinary-artschefs.png")); // NOI18N
        cheficon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cheficonMouseClicked(evt);
            }
        });

        lchef.setText("culinary-artschefs");
        lchef.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lchefMouseClicked(evt);
            }
        });

        lnextpg.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lnextpg.setForeground(new java.awt.Color(255, 0, 153));
        lnextpg.setText("NEXT PAGE");
        lnextpg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 255), 2, true));
        lnextpg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lnextpgMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lcs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lca))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ltheatre, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(theatreicon))
                                .addGap(125, 125, 125)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(philosicon)
                                    .addComponent(lphilos))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(ldancer)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(larchaelogy))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(archicon)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(larchi))
                                            .addComponent(dancericon))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lcivils)
                                            .addComponent(civilsicon)
                                            .addComponent(archaelogyicon))))
                                .addGap(32, 32, 32))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(csicon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(caicon, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(gamingicon)
                        .addGap(118, 118, 118)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(socialicon)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lsocial)
                                    .addComponent(merchanticon)
                                    .addComponent(lmerchant)
                                    .addComponent(cheficon)
                                    .addComponent(lchef))))
                        .addGap(44, 44, 44))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(lanimation))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(animation)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lcrea)
                            .addComponent(creativeicon))
                        .addGap(66, 66, 66))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(chemistryicon)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(lchemistry))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lgame)
                                    .addComponent(coasticon)
                                    .addComponent(lcoast))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lnextpg)
                .addGap(336, 336, 336))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(csicon)
                        .addGap(18, 18, 18)
                        .addComponent(lcs))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(caicon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lca, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(creativeicon)
                        .addGap(12, 12, 12)
                        .addComponent(lcrea))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(animation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lanimation, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(socialicon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lsocial))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(philosicon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lphilos))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(theatreicon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ltheatre))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(gamingicon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lgame)
                                .addGap(6, 6, 6)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(archicon)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(coasticon)
                                .addComponent(civilsicon))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(merchanticon)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(larchi)
                        .addGap(47, 47, 47)
                        .addComponent(dancericon))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lcivils)
                            .addComponent(lcoast)
                            .addComponent(lmerchant))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(archaelogyicon, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chemistryicon, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cheficon, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(lnextpg)
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ldancer)
                    .addComponent(larchaelogy)
                    .addComponent(lchemistry)
                    .addComponent(lchef))
                .addGap(111, 111, 111))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void csiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_csiconMouseClicked
        // TODO add your handling code here:
        cs com = new cs();
        com.setVisible(true);
        this.dispose();
      
    }//GEN-LAST:event_csiconMouseClicked

    private void lcsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lcsMouseClicked
        // TODO add your handling code here:
        cs com = new cs();
        com.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lcsMouseClicked

    private void caiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caiconMouseClicked
        // TODO add your handling code here:
        ca com = new ca();
        com.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_caiconMouseClicked

    private void lcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lcaMouseClicked
        // TODO add your handling code here:
         ca com = new ca();
        com.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lcaMouseClicked

    private void animationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_animationMouseClicked
        // TODO add your handling code here:
         animation com = new animation();
        com.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_animationMouseClicked

    private void lanimationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lanimationMouseClicked
        // TODO add your handling code here:
         animation com = new animation();
        com.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lanimationMouseClicked

    private void creativeiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creativeiconMouseClicked
        // TODO add your handling code here:
         creative com = new creative();
        com.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_creativeiconMouseClicked

    private void lcreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lcreaMouseClicked
        // TODO add your handling code here:
         creative com = new creative();
        com.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lcreaMouseClicked

    private void theatreiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_theatreiconMouseClicked
        // TODO add your handling code here:
        thearte com = new thearte();
        com.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_theatreiconMouseClicked

    private void ltheatreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ltheatreMouseClicked
        // TODO add your handling code here:
         thearte com = new thearte();
        com.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ltheatreMouseClicked

    private void archiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_archiconMouseClicked
        // TODO add your handling code here:
        architect com = new architect();
        com.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_archiconMouseClicked

    private void larchiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_larchiMouseClicked
        // TODO add your handling code here:
        architect com = new architect();
        com.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_larchiMouseClicked

    private void dancericonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dancericonMouseClicked
        // TODO add your handling code here:
        dancer com = new dancer();
        com.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dancericonMouseClicked

    private void ldancerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ldancerMouseClicked
        // TODO add your handling code here:
        dancer com = new dancer();
        com.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ldancerMouseClicked

    private void lnextpgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lnextpgMouseClicked
        // TODO add your handling code here:
         nafter12th twe = new nafter12th();
        twe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lnextpgMouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        homepage ten = new homepage();
        ten.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void philosiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_philosiconMouseClicked
        // TODO add your handling code here:
        philosophy ph= new philosophy();
        ph.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_philosiconMouseClicked

    private void lphilosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lphilosMouseClicked
        // TODO add your handling code here:
         philosophy ph= new philosophy();
        ph.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lphilosMouseClicked

    private void gamingiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gamingiconMouseClicked
        // TODO add your handling code here:
         graphicaldesigner ph= new graphicaldesigner();
        ph.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gamingiconMouseClicked

    private void lgameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgameMouseClicked
        // TODO add your handling code here:
         graphicaldesigner ph= new graphicaldesigner();
        ph.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lgameMouseClicked

    private void socialiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_socialiconMouseClicked
        // TODO add your handling code here:
        socialwork ph= new socialwork();
        ph.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_socialiconMouseClicked

    private void lsocialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lsocialMouseClicked
        // TODO add your handling code here: socialwork ph= new socialwork();
        socialwork ph= new socialwork();
        ph.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lsocialMouseClicked

    private void civilsiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_civilsiconMouseClicked
        // TODO add your handling code here:
        civilservice ph= new civilservice();
        ph.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_civilsiconMouseClicked

    private void lcivilsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lcivilsMouseClicked
        // TODO add your handling code here:
         civilservice ph= new civilservice();
        ph.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lcivilsMouseClicked

    private void coasticonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coasticonMouseClicked
        // TODO add your handling code here:
        coastguard ph= new coastguard();
        ph.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_coasticonMouseClicked

    private void lcoastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lcoastMouseClicked
        // TODO add your handling code here:
         coastguard ph= new coastguard();
        ph.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lcoastMouseClicked

    private void merchanticonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_merchanticonMouseClicked
        // TODO add your handling code here:
        merchantnavy ph= new merchantnavy();
        ph.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_merchanticonMouseClicked

    private void lmerchantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lmerchantMouseClicked
        // TODO add your handling code here:
        merchantnavy ph= new merchantnavy();
        ph.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lmerchantMouseClicked

    private void archaelogyiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_archaelogyiconMouseClicked
        // TODO add your handling code here:
        archeology ph= new archeology();
        ph.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_archaelogyiconMouseClicked

    private void larchaelogyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_larchaelogyMouseClicked
        // TODO add your handling code here:
        archeology ph= new archeology();
        ph.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_larchaelogyMouseClicked

    private void chemistryiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chemistryiconMouseClicked
        // TODO add your handling code here:
        chemstry ph= new chemstry();
        ph.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_chemistryiconMouseClicked

    private void lchemistryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lchemistryMouseClicked
        // TODO add your handling code here:
        chemstry ph= new chemstry();
        ph.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lchemistryMouseClicked

    private void cheficonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cheficonMouseClicked
        // TODO add your handling code here:
        chef ph= new chef();
        ph.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cheficonMouseClicked

    private void lchefMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lchefMouseClicked
        // TODO add your handling code here:
         chef ph= new chef();
        ph.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lchefMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nafter10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nafter10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nafter10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nafter10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nafter10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel animation;
    private javax.swing.JLabel archaelogyicon;
    private javax.swing.JLabel archicon;
    private javax.swing.JLabel caicon;
    private javax.swing.JLabel cheficon;
    private javax.swing.JLabel chemistryicon;
    private javax.swing.JLabel civilsicon;
    private javax.swing.JLabel coasticon;
    private javax.swing.JLabel creativeicon;
    private javax.swing.JLabel csicon;
    private javax.swing.JLabel dancericon;
    private javax.swing.JLabel gamingicon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lanimation;
    private javax.swing.JLabel larchaelogy;
    private javax.swing.JLabel larchi;
    private javax.swing.JLabel lca;
    private javax.swing.JLabel lchef;
    private javax.swing.JLabel lchemistry;
    private javax.swing.JLabel lcivils;
    private javax.swing.JLabel lcoast;
    private javax.swing.JLabel lcrea;
    private javax.swing.JLabel lcs;
    private javax.swing.JLabel ldancer;
    private javax.swing.JLabel lgame;
    private javax.swing.JLabel lmerchant;
    private javax.swing.JLabel lnextpg;
    private javax.swing.JLabel lphilos;
    private javax.swing.JLabel lsocial;
    private javax.swing.JLabel ltheatre;
    private javax.swing.JLabel merchanticon;
    private javax.swing.JLabel philosicon;
    private javax.swing.JLabel socialicon;
    private javax.swing.JLabel theatreicon;
    // End of variables declaration//GEN-END:variables
}
